### ISSUE TITLE
Failed to precompile on GitHub Actions

### ISSUE THREAD

**Issue by jkosata** [SciML/Sundials.jl#370] opened 2022-08-31 16:45 UTC
Sundials 4.10.0. (as a dependency of DifferentialEquations) fails to precompile on GitHub Actions, both with Julia 1.7 and 1.8.
see report at https://github.com/NonlinearOscillations/HarmonicBalance.jl/runs/8117545349?check_suite_focus=true

Other SciML packages (OrdinaryDiffEq, StochasticDiffEq, DifferentialEquations, DelayDiffEq) also do not compile there.

Capping the version to 4.9.4 makes it precompile ok, but the other packages still fail. 

Locally, everything works fine, which is making this hard to debug ..

**Comment by ChrisRackauckas** [comment] 2022-08-31 16:49
The v1.7 issue seems unrelated. We can chat about that and getting your versions updated correctly, but that doesn't seem related to Sundials.

For the v1.8 issue, see https://github.com/SciML/Sundials.jl/issues/367

**Comment by ChrisRackauckas** [comment] 2022-08-31 16:53
Closing as a duplicate of #367

**Closed by ChrisRackauckas** 2022-08-31 16:53 UTC
